AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Cognito User Pool and Client'

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage (e.g., dev, prod)

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'auth-stack-user-pool-${Stage}'
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'auth-stack-client-${Stage}'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub 'auth-stack-UserPoolId-${Stage}'

  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub 'auth-stack-UserPoolClientId-${Stage}'
