Resources:
  LessonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.lessonsTable}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.progressTable}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: lessonId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: lessonId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST